### ISSUE TITLE
COPY failed

### ISSUE THREAD

**Issue by bipinkrish** [bots-house/docker-telegram-bot-api#20]
file not found in build context or excluded by .dockerignore: stat upstream/CMakeLists.txt: file does not exist

**Comment by bipinkrish** [comment]
> file not found in build context or excluded by .dockerignore: stat upstream/CMakeLists.txt: file does not exist

sorry my mistake

**Comment by StepsOnes** [comment]
> > файл не найден в контексте сборки или исключен .dockerignore: stat upstream/CMakeLists.txt: файл не существует
> 
> Извините моя ошибка

how u fixed this?

**Comment by bipinkrish** [comment]
> how u fixed this?

It triggers when you push it to upstream
