### ISSUE TITLE
Reverse proxy

### ISSUE THREAD

**Issue by InsanusMokrassar** [bots-house/docker-telegram-bot-api#4]
I am trying to use this server behind the reverse proxy with custom subpath. Is it possible to set up information about it to bot? Currently I am getting the next answer from `Telegram` system due to an incorrect subpath:

```json
{"ok":false,"error_code":404,"description":"Not Found"}
```

**Comment by mr-linch** [comment]
You need to rewrite the path at the reverse proxy level. But it is better to place on a separate domain / subdomain.
